//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FOI_Log.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class FOI_Department
    {
        public int FOI_Department_Code { get; set; }
        public Nullable<int> FOI_Ref { get; set; }
        public Nullable<int> Department_Code { get; set; }
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        [Display(Name = "Date Department Due To Respond")]
        public Nullable<System.DateTime> Date_Department_Due_To_Respond { get; set; }
        [Display(Name = "First IG Team Chase")]
        public Nullable<System.DateTime> First_IG_Team_Chase { get; set; }
        [Display(Name = "Information Received From Department")]
        public Nullable<System.DateTime> Information_Received_From_Department { get; set; }

        public virtual FOI FOI { get; set; }
        public virtual Ref_Department Ref_Department { get; set; }
    }
}
