//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FOI_Log.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class FOI_LOGEntities : DbContext
    {
        public FOI_LOGEntities()
            : base("name=FOI_LOGEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FOI> FOIs { get; set; }
        public virtual DbSet<FOI_Department> FOI_Department { get; set; }
        public virtual DbSet<Ref_Area_of_Interest> Ref_Area_of_Interest { get; set; }
        public virtual DbSet<Ref_Department> Ref_Department { get; set; }
        public virtual DbSet<Ref_Department_Directors_Email> Ref_Department_Directors_Email { get; set; }
        public virtual DbSet<Ref_Department_Managers_Email> Ref_Department_Managers_Email { get; set; }
        public virtual DbSet<Ref_Status> Ref_Status { get; set; }
    
        public virtual int SP_UPDATE_FOI_DEPARTMENTS(Nullable<int> fOIREF, Nullable<int> departmentCode, Nullable<System.DateTime> first_IG_Team_Chase, Nullable<System.DateTime> information_Recieved_From_Department)
        {
            var fOIREFParameter = fOIREF.HasValue ?
                new ObjectParameter("FOIREF", fOIREF) :
                new ObjectParameter("FOIREF", typeof(int));
    
            var departmentCodeParameter = departmentCode.HasValue ?
                new ObjectParameter("DepartmentCode", departmentCode) :
                new ObjectParameter("DepartmentCode", typeof(int));
    
            var first_IG_Team_ChaseParameter = first_IG_Team_Chase.HasValue ?
                new ObjectParameter("First_IG_Team_Chase", first_IG_Team_Chase) :
                new ObjectParameter("First_IG_Team_Chase", typeof(System.DateTime));
    
            var information_Recieved_From_DepartmentParameter = information_Recieved_From_Department.HasValue ?
                new ObjectParameter("Information_Recieved_From_Department", information_Recieved_From_Department) :
                new ObjectParameter("Information_Recieved_From_Department", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_UPDATE_FOI_DEPARTMENTS", fOIREFParameter, departmentCodeParameter, first_IG_Team_ChaseParameter, information_Recieved_From_DepartmentParameter);
        }
    
        public virtual int SP_UPDATE_FOI_LOG(Nullable<System.DateTime> fOI_Received, Nullable<System.DateTime> first_IG_Team_Chase, Nullable<System.DateTime> information_Received_From_Department, string response_Sent_to_Requestor, string association_or_Previous_Request, string requestor_Name, string requestor_Email, string information_Sought, string comments, Nullable<int> status_Code, Nullable<int> area_of_Interest_Code, string created_By, Nullable<System.DateTime> created_Date, string updated_By, Nullable<System.DateTime> updated_Date, string deleted_By, Nullable<System.DateTime> deleted_Date, string head_DQSP_Approval, Nullable<System.DateTime> dSQP_Approved_Date, string director_Approval, Nullable<System.DateTime> director_Approval_Date, Nullable<bool> completed_Flag)
        {
            var fOI_ReceivedParameter = fOI_Received.HasValue ?
                new ObjectParameter("FOI_Received", fOI_Received) :
                new ObjectParameter("FOI_Received", typeof(System.DateTime));
    
            var first_IG_Team_ChaseParameter = first_IG_Team_Chase.HasValue ?
                new ObjectParameter("First_IG_Team_Chase", first_IG_Team_Chase) :
                new ObjectParameter("First_IG_Team_Chase", typeof(System.DateTime));
    
            var information_Received_From_DepartmentParameter = information_Received_From_Department.HasValue ?
                new ObjectParameter("Information_Received_From_Department", information_Received_From_Department) :
                new ObjectParameter("Information_Received_From_Department", typeof(System.DateTime));
    
            var response_Sent_to_RequestorParameter = response_Sent_to_Requestor != null ?
                new ObjectParameter("Response_Sent_to_Requestor", response_Sent_to_Requestor) :
                new ObjectParameter("Response_Sent_to_Requestor", typeof(string));
    
            var association_or_Previous_RequestParameter = association_or_Previous_Request != null ?
                new ObjectParameter("Association_or_Previous_Request", association_or_Previous_Request) :
                new ObjectParameter("Association_or_Previous_Request", typeof(string));
    
            var requestor_NameParameter = requestor_Name != null ?
                new ObjectParameter("Requestor_Name", requestor_Name) :
                new ObjectParameter("Requestor_Name", typeof(string));
    
            var requestor_EmailParameter = requestor_Email != null ?
                new ObjectParameter("Requestor_Email", requestor_Email) :
                new ObjectParameter("Requestor_Email", typeof(string));
    
            var information_SoughtParameter = information_Sought != null ?
                new ObjectParameter("Information_Sought", information_Sought) :
                new ObjectParameter("Information_Sought", typeof(string));
    
            var commentsParameter = comments != null ?
                new ObjectParameter("Comments", comments) :
                new ObjectParameter("Comments", typeof(string));
    
            var status_CodeParameter = status_Code.HasValue ?
                new ObjectParameter("Status_Code", status_Code) :
                new ObjectParameter("Status_Code", typeof(int));
    
            var area_of_Interest_CodeParameter = area_of_Interest_Code.HasValue ?
                new ObjectParameter("Area_of_Interest_Code", area_of_Interest_Code) :
                new ObjectParameter("Area_of_Interest_Code", typeof(int));
    
            var created_ByParameter = created_By != null ?
                new ObjectParameter("Created_By", created_By) :
                new ObjectParameter("Created_By", typeof(string));
    
            var created_DateParameter = created_Date.HasValue ?
                new ObjectParameter("Created_Date", created_Date) :
                new ObjectParameter("Created_Date", typeof(System.DateTime));
    
            var updated_ByParameter = updated_By != null ?
                new ObjectParameter("Updated_By", updated_By) :
                new ObjectParameter("Updated_By", typeof(string));
    
            var updated_DateParameter = updated_Date.HasValue ?
                new ObjectParameter("Updated_Date", updated_Date) :
                new ObjectParameter("Updated_Date", typeof(System.DateTime));
    
            var deleted_ByParameter = deleted_By != null ?
                new ObjectParameter("Deleted_By", deleted_By) :
                new ObjectParameter("Deleted_By", typeof(string));
    
            var deleted_DateParameter = deleted_Date.HasValue ?
                new ObjectParameter("Deleted_Date", deleted_Date) :
                new ObjectParameter("Deleted_Date", typeof(System.DateTime));
    
            var head_DQSP_ApprovalParameter = head_DQSP_Approval != null ?
                new ObjectParameter("Head_DQSP_Approval", head_DQSP_Approval) :
                new ObjectParameter("Head_DQSP_Approval", typeof(string));
    
            var dSQP_Approved_DateParameter = dSQP_Approved_Date.HasValue ?
                new ObjectParameter("DSQP_Approved_Date", dSQP_Approved_Date) :
                new ObjectParameter("DSQP_Approved_Date", typeof(System.DateTime));
    
            var director_ApprovalParameter = director_Approval != null ?
                new ObjectParameter("Director_Approval", director_Approval) :
                new ObjectParameter("Director_Approval", typeof(string));
    
            var director_Approval_DateParameter = director_Approval_Date.HasValue ?
                new ObjectParameter("Director_Approval_Date", director_Approval_Date) :
                new ObjectParameter("Director_Approval_Date", typeof(System.DateTime));
    
            var completed_FlagParameter = completed_Flag.HasValue ?
                new ObjectParameter("Completed_Flag", completed_Flag) :
                new ObjectParameter("Completed_Flag", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_UPDATE_FOI_LOG", fOI_ReceivedParameter, first_IG_Team_ChaseParameter, information_Received_From_DepartmentParameter, response_Sent_to_RequestorParameter, association_or_Previous_RequestParameter, requestor_NameParameter, requestor_EmailParameter, information_SoughtParameter, commentsParameter, status_CodeParameter, area_of_Interest_CodeParameter, created_ByParameter, created_DateParameter, updated_ByParameter, updated_DateParameter, deleted_ByParameter, deleted_DateParameter, head_DQSP_ApprovalParameter, dSQP_Approved_DateParameter, director_ApprovalParameter, director_Approval_DateParameter, completed_FlagParameter);
        }
    }
}
