//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FOI_Log.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Ref_Department
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ref_Department()
        {
            this.FOI_Department = new HashSet<FOI_Department>();
            this.Ref_Department_Directors_Email = new HashSet<Ref_Department_Directors_Email>();
            this.Ref_Department_Managers_Email = new HashSet<Ref_Department_Managers_Email>();
        }

        public int Department_Code { get; set; }
        public string Department { get; set; }
        [Display(Name = "Days to Respond")]
        public Nullable<int> Days_to_Respond { get; set; }
        [Display(Name = "Department Email")]
        public string Department_Email { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FOI_Department> FOI_Department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ref_Department_Directors_Email> Ref_Department_Directors_Email { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ref_Department_Managers_Email> Ref_Department_Managers_Email { get; set; }
    }
}
